irrigation:
  schedules:
    - name: schedule_a
      events:
        - name: "ON"
          timestamp: "18:35:00"
          command: turnOnCommand
          devices:
            - relayA
            - relayB
        - name: "OFF"
          timestamp: "18:40:00"
          command: turnOffCommand
          devices:
            - relayA
            - relayB
  #  - name: schedule_b
  #    events:
  #      - name: MEASURE
  #        timestamp:
  #        scheduledDays:
  #          - MONDAY
  #          - WEDNESDAY
  #          - FRIDAY
  #        command: measureCommand
  #        devices:
  #          - sensor
